name: dpg-gastby-build
description: 'Executes run-script build in a Gastby project'
runs:
  using: "composite"
  steps:
    - run: npm run-script build
      shell: bash
    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: output-files
        path: public    
